### ISSUE TITLE
更新后，报错，utf-8' codec can't decode byte 0xbf in position 956

### ISSUE THREAD

**Issue by comcsao** [SmileSmith/autoAnswer#10]
Traceback (most recent call last):
  File "server.py", line 30, in <module>
    run()
  File "server.py", line 20, in run
    if check_hosts(HOST):
  File "E:\autoAnswer\src\units\method.py", line 138, in check_hosts
    read_content = read_file.read()
  File "E:\Python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 956: inval
d start byte
查了下所有文件的编码，无异常，只知道是编码问题造成，具体如何解决，之前一直都是正常的。
问题已经解决：Hosts文件的编码必须为UTF-8，不然会报错，建议加入这条注意事项。

**Comment by SmileSmith** [comment]
已经catch
    except UnicodeDecodeError:
        print("不支持的编码类型，请切换解码放式或自行修改文件编码类型")
